### ISSUE TITLE
能否增加python2.7的支持?

### ISSUE THREAD

**Issue by loadstarCN** [nosix/raspberry-gpio-emulator#2]
>>> import RPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/RPi/GPIO.py", line 5, in <module>
    from .launcher import ui
  File "/usr/local/lib/python2.7/site-packages/RPi/launcher.py", line 3, in <module>
    from .pipe import Pipe
  File "/usr/local/lib/python2.7/site-packages/RPi/pipe.py", line 1, in <module>
    from builtins import bytes
ImportError: No module named builtins

========================================
使用pip install future
添加builtins的支持后

显示如下错误：
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import RPi.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: not holding the import lock
>>> Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 592, in callit
    func(*args)
  File "/usr/local/lib/python2.7/site-packages/RPi/ui_server.py", line 90, in __update
    raise ex
IOError: [Errno 35] Resource temporarily unavailable

**Comment by nosix** [comment]
Currently, there are no plans to support Python 2.x. I would like to promote the transition to Python 3.x.

**Comment by guilfer-dev** [comment]
> Currently, there are no plans to support Python 2.x. I would like to promote the transition to Python 3.x.

You could close this issue, after all, there is a warning in the readme.
Btw, thanks for your code! o/

**Comment by nosix** [comment]
Thank you for your comment. I hope the code helps.

It's just the right time, so I'll close this issue.
