### ISSUE TITLE
Cannot change pin mode after initial setup

### ISSUE THREAD

**Issue by nandlab** [nosix/raspberry-gpio-emulator#8]
Hello nosix,
thanks for sharing this useful GPIO simulation library!
In my program I want to first setup a pin as input (High-Z), and after a game is completed set it to output LOW. This works fine with the real RPi GPIO library. But with the emulator library, this error is thrown:
```
Traceback (most recent call last):
  File "./riddle_beer_dispenser.py", line 105, in <module>
    main()
  File "./riddle_beer_dispenser.py", line 92, in main
    GPIO.setup(solvedPin, GPIO.OUT, initial=GPIO.LOW)
  File "/home/dan/.local/lib/python3.8/site-packages/RPi/GPIO.py", line 159, in setup
    __setup(__to_channel(channel), state, initial, pull_up_down)
  File "/home/dan/.local/lib/python3.8/site-packages/RPi/GPIO.py", line 168, in __setup
    assert channel not in __pins_dict, 'GPIO is already setup'
AssertionError: GPIO is already setup
```
I think it should be possible to change the pin mode once more after initial setup. Can you please fix it?

**Comment by nosix** [comment]
Thank you for your report.

It looks like an unnecessary check, so I deleted the assertion.

**Comment by nandlab** [comment]
Now it works, thank you!
